# Generated by Django 3.2.12 on 2022-07-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blood_form_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_form',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blood_form',
            name='report',
            field=models.FileField(upload_to='media'),
        ),
    ]
