# Generated by Django 3.2.12 on 2022-07-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220717_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_form',
            name='gender',
        ),
    ]
