# Generated by Django 3.2.12 on 2022-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blood_form_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_form',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
