# Generated by Django 3.2.12 on 2022-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blood_form_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_form',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
