# Generated by Django 3.2.12 on 2022-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_extra_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_extra_contact',
            name='blood_group',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
